### ISSUE TITLE
Test description doesn't make sense—copy/pasta?

### ISSUE THREAD

**Issue by wifelette** [learn-co-curriculum/react-component-mounting-lab#9]
https://github.com/learn-co-curriculum/react-component-mounting-lab/blob/e90a8eac13ea7f08e1f697e96b49f92e97624e4f/test/index.test.js#L16

The test talks about "adding a quote" but unless I'm missing something, that doesn't make sense? Guessing it's a copy/paste from some other lab. 

Suggested alternative: "should start with one Timer already running" since it's testing to make sure you put `this.handleAddTimer()` into `componentDidMount`.

**Comment by Sdcrouse** [comment]
That's a good alternative, but I don't think the Timer has to be running in order to pass the test.

For that part of the lab, the README says, "If you've got it working and have the app served up on a browser tab, you'll see that, upon refresh, a timer will be present. The timer is still not working, but that's okay for now."

I'll open a PR for this in just a moment.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

The materials have been updated and we believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
